name: 'CI'
on: [push]

jobs:
    ci:
        runs-on: ubuntu-latest
        container: elixir:1.13.3-alpine
        steps:
            - uses: actions/checkout@v1
            - name: Install make
              run: apk add make
            - name: Install hex
              run: mix local.hex --force
            - name: Install rebar
              run: mix local.rebar --force
            - name: Run the "ci" make target
              run: make ci
