name: 'CI'
on: [push]

jobs:
    ci:
        runs-on: ubuntu-latest
        container: elixir:1.13.3-alpine
        steps:
            - uses: actions/checkout@v1
            - run: |
                  apk add make

                  mix local.hex --force
                  mix local.rebar --force

                  make ci
              name: Run in container
